version: "0.1"

services:
  db:
    restart: always
    container_name: database
    image: postgres:16.1
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/db-data.txt:/data-import/db-data.txt
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - 5432:5432

volumes:
  pgdata:
